name: Translation
description: Add or improve translation
labels: ['translation']
body:
  - type: markdown
      attributes:
        value: |
        Please use https://localazy.com/p/zod-i18n to add or modify translation then create a pull request
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you think would be an helpful addition to the translations.
    validations:
      required: true
